### ISSUE TITLE
Append new attributes by default, add option to override behaviour

### ISSUE THREAD

**Issue by y0nei** [jpsca/jinjax#47]
The `attrs.render()` usage is really powerful. It would be great if one could do something like this:

`Component.jinja`:
```jinja
{#def type="info", hidden=false #}

{% do attrs.set(class=hidden) if hidden %}
{% do attrs.set(class="{{ type ~ '-modal'}}") %}

<div {{ attrs.render() }} class="modal">...</div>
```
Using the component:
```html
<Component type="info" id="context" hidden />
```

---

My current solution is doing something like this:
```jinja
{#def type="info", context="", hidden=false #}

<div {% if context %} id="{{ context }}" {% endif %}
     class="modal {{ type ~ '-modal' }} {{ 'hidden' if hidden }}">
   ...
</div>
```
Using the component:
```html
<Component type="info" context="context" hidden />
```

**Comment by jpsca** [comment]
I don't understand fully what are you asking... 

You can have a default attribute using `attrs,setdefault(name=value)`.
So if your component is like this:

Component.jinja
```jinja
{% do attrs.setdefault(id="default") %}
<div {{ attrs.render() }}></div>
```

This:

```jinja
<Component id="custom-id" />
<Component />
````
will render as:

```html
<div id="custom-id"></div>
<div id="default"></div>
```
---

Notice that classes work differently than other attributes in the sense that `{% do attrs.set(class="a") %}` and `{{ attrs.render(class="b") }}` add the classes "a" and "b" to those in the class attribute (if exists) instead of overriding it.

Example:

For:

Component.jinja
```jinja
<div {{ attrs.render(class="modal", id="hardcoded") }}></div>
```

this: 

```jinja
<Component class="info" id="nope" />
````

will render as 

```html
<div class="info modal" id="hardcoded"></div>
```
