### ISSUE TITLE
Using `catalog.get_middleware` with FastAPI

### ISSUE THREAD

**Issue by MLackner** [jpsca/jinjax#72]
Hi,

I have a problem getting the necessary middleware to run with FastAPI. The documention is specific to a Flask app:

```py
from flask import Flask
from jinjax import Catalog

app = Flask(__name__)

# Here we add the Flask Jinja globals, filters, etc., like `url_for()`
catalog = jinjax.Catalog(jinja_env=app.jinja_env)

catalog.add_folder("myapp/components")

app.wsgi_app = catalog.get_middleware(
    app.wsgi_app,
    autorefresh=app.debug,
)
```

I was not able to transfer that example to FastAPI. Did anyone get this to work? 😊

**Comment by Kokoserver** [comment]
i also tried this but the result is a string rather than html

**Comment by Kokoserver** [comment]
@MLackner try this

# I'm using lilya framework, but this works now, 
# this should be the equivalent with fastapi
from lilya.templating import Jinja2Template
from jinjax import Catalog


templates = Jinja2Template(directory="templates")

catalog = Catalog(jinja_env=templates.env)
catalog.add_folder("templates/components")


@router.get("/")
async def welcome() -> Response:
    result = catalog.render("Hello", name="Welcome")
    return Response(result, status_code=200, media_type="text/html")

**Comment by mardiros** [comment]
Hello @MLackner 

I use fastapi with JinjaX without using the get_middeware. I create a FastAPI dependency instead.

Unfortunatly, my code is mode complex than the lilya exemple above,
but you can read a bit of how it works here:


I have a jinjax renderer helper here that also handle CSRF tokens since I post form.

https://github.com/mardiros/fastlife/blob/main/src/fastlife/templating/renderer/jinjax.py


And I  have a binding that get the renderer and return the renderer in order to render it.

https://github.com/mardiros/fastlife/blob/main/src/fastlife/templating/binding.py

You can note here that the magic content/type is set with some code like

```python
data = catalog.render("HelloWorld",  ...)
resp = Response(data, headers={"Content-Type": content_type})
```


Then, an exemple of how I use the template dependency.
https://github.com/mardiros/fastlife/blob/main/tests/fastlife_app/views/home.py#L15

**Comment by Noreu** [comment]
Simply pass JinjaX as extension to Jinja2Templates :

`import jinjax
from fastapi import FastAPI, Request
from fastapi.templating import Jinja2Templates

app = FastAPI()

templates = Jinja2Templates(directory="templates")

templates.env.add_extension(jinjax.JinjaX)
catalog = jinjax.Catalog(jinja_env=templates.env)
catalog.add_folder("templates/components")

@app.get("/")
def get_index(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})
`
